In [1]:
import undetected_chromedriver as uc
from bs4 import BeautifulSoup 
from re import search
import pandas as pd
import requests

In [2]:
def get_parameters(sity):
    if sity == 'Belgrade': parameters = {'locId': 1655, 'locName': 'Belgrade,%20Serbia%20Area', 'num_pages':23}
    if sity == 'Moscow': parameters = {'locId': 1159, 'locName': 'Moscow,%20Russia%20Area', 'num_pages':44}
    if sity == 'Saint Petersburg': parameters = {'locId': 1158, 'locName': 'Saint%20Petersburg,%20Russia%20Area', 'num_pages':20 }
    return parameters

In [3]:
def get_companies(parameters):
    companies = []
    driver = uc.Chrome()
    for page in range(1, parameters['num_pages']+1):
        driver.get('https://www.glassdoor.com/Explore/browse-companies.htm?overall_rating_low=3&sector=10013&locType=M&page={i}\
        &locId={my_dict[locId]}&locName={my_dict[locName]}'.format(i = page, my_dict=parameters))
        HTML = driver.page_source
        soup = BeautifulSoup(HTML , 'html.parser')
        company_information = soup.find_all('span', class_ ="align-items-center mb-xsm")
        for company_name_and_rating in company_information:
            company_name = search(r'(\D+)', company_name_and_rating.text).group(1) 
            companies.append(company_name)
    return companies

In [4]:
parameters_for_Belgrade = get_parameters('Belgrade')
parameters_for_Moscow = get_parameters('Moscow')
parameters_for_Saint_Petersburg = get_parameters('Saint Petersburg')

In [5]:
companies_in_Belgrade =  pd.DataFrame(get_companies(parameters_for_Belgrade))
companies_in_Saint_Petersburg =  pd.DataFrame(get_companies(parameters_for_Moscow))
companies_in_Moscow =  pd.DataFrame(get_companies(parameters_for_Saint_Petersburg))

In [6]:
companies_in_Moscow_or_Saint_Petersburg = pd.merge(companies_in_Moscow, companies_in_Saint_Petersburg,  how='outer').drop_duplicates()
companies_in_MSK_or_Petersburg_and_Belgrade  = pd.merge(companies_in_Moscow_or_Saint_Petersburg, companies_in_Belgrade, how='inner')

In [7]:
companies_in_MSK_or_Petersburg_and_Belgrade

                                   0
0                             Oracle
1                                SAP
2                             Google
3                  Intel Corporation
4                          Microsoft
5                                IBM
6                      Grid Dynamics
7                        Booking.com
8                     Quest Software
9                             Skyeng
10                         Tietoevry
11                    DXC Technology
12                     Cisco Systems
13                      DONE by NONE
14                            Toptal
15                           Playrix
16                 HERE Technologies
17                           Akvelon
18                   Thomson Reuters
19                           Nielsen
20                         Honeywell
21                      Robert Bosch
22  Hewlett Packard Enterprise | HPE
23                     SAS Institute
24                            Amazon
25                              Atos
26                           Fujitsu
27                               NCR
28                         NielsenIQ
29                            TomTom
30                           Nutanix
31                        Lionbridge
32                             Skype
33                  Orion Innovation
34                          Devoteam
35                               YES
36                          Smartcat